version: "3.3"

services:
  ros_master:
    image: ros:latest
    container_name: rosnode_master
    hostname: rosmaster
    ports:
      - "11311:11311"
    networks:
      - rosdocker
    command:
      - roscore

  ros_server:
    container_name: ros_server
    hostname: ros_server
    build: 
        context: .
        dockerfile: ./server/Dockerfile
    depends_on:
      - "ros_master"
    ports:
      - "10000:10000"
    environment:
      - "ROS_MASTER_URI=http://ros_master:11311"
    networks:
      - rosdocker

  ros_client:
    container_name: ros_client
    hostname: ros_client
    build: 
        context: .
        dockerfile: ./client/Dockerfile
    depends_on:
      - "ros_master"
      - "ros_server"
    ports:
      - "10001:10001"
    environment:
      - "ROS_MASTER_URI=http://ros_master:11311"
    networks:
      - rosdocker

networks:
  rosdocker: {}
